#!/bin/bash
# NEXTFLOW TASK: Generate_output (1)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_container_env() {
cat << EOF
export PATH="/Users/uwvirongs/Documents/Michelle/lava/bin:\$PATH"
EOF
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /Users/uwvirongs/Documents/Michelle/lava/test_data/work/9a/d5c81153edb9052478b8d5b2e55a7e/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    docker rm $NXF_BOXID &>/dev/null || true
    exit $exit_status
}

on_term() {
    set +e
    docker kill $NXF_BOXID
}

nxf_launch() {
    docker run -i --memory 1024m -v /Users/uwvirongs/Documents/Michelle/lava:/Users/uwvirongs/Documents/Michelle/lava -v "$PWD":"$PWD" -w "$PWD" --entrypoint /bin/bash --name $NXF_BOXID quay.io/vpeddu/lava_image:latest -c "eval $(nxf_container_env); /bin/bash /Users/uwvirongs/Documents/Michelle/lava/test_data/work/9a/d5c81153edb9052478b8d5b2e55a7e/.command.sh"
}

nxf_stage() {
    true
    # stage input files
    rm -f Example1_file1.fastq
    rm -f Example1_file1.fastq.complex.log
    rm -f Example1_file1.fastq.reads.csv
    rm -f Example1_file1.fastq.csv
    rm -f Example1_file2.fastq
    rm -f Example1_file2.fastq.complex.log
    rm -f Example1_file2.fastq.reads.csv
    rm -f Example1_file2.fastq.csv
    rm -f merged.csv
    rm -f proteins.csv
    rm -f Example1_file2.fastq.genomecov
    rm -f Example1_file1.fastq.genomecov
    rm -f Example1_file1.fastq.vcf
    rm -f Example1_file2.fastq.vcf
    rm -f ribosomal_start.txt
    ln -s /Users/uwvirongs/Documents/Michelle/lava/test_data/Example1_file1.fastq Example1_file1.fastq
    ln -s /Users/uwvirongs/Documents/Michelle/lava/test_data/work/25/28acdea475ad7b8d463e2c211a2802/Example1_file1.fastq.complex.log Example1_file1.fastq.complex.log
    ln -s /Users/uwvirongs/Documents/Michelle/lava/test_data/work/49/3ea74c025cc3efd93116d8061882b7/reads.csv Example1_file1.fastq.reads.csv
    ln -s /Users/uwvirongs/Documents/Michelle/lava/test_data/work/49/3ea74c025cc3efd93116d8061882b7/Example1_file1.fastq.csv Example1_file1.fastq.csv
    ln -s /Users/uwvirongs/Documents/Michelle/lava/test_data/Example1_file2.fastq Example1_file2.fastq
    ln -s /Users/uwvirongs/Documents/Michelle/lava/test_data/work/c5/9a79d8733b337a6e08cbb9626d69d2/Example1_file2.fastq.complex.log Example1_file2.fastq.complex.log
    ln -s /Users/uwvirongs/Documents/Michelle/lava/test_data/work/b7/62d6edbff16357c9da3317df2608e9/reads.csv Example1_file2.fastq.reads.csv
    ln -s /Users/uwvirongs/Documents/Michelle/lava/test_data/work/b7/62d6edbff16357c9da3317df2608e9/Example1_file2.fastq.csv Example1_file2.fastq.csv
    ln -s /Users/uwvirongs/Documents/Michelle/lava/test_data/work/23/56ccf88c2979202de4aacd412bd78d/merged.csv merged.csv
    ln -s /Users/uwvirongs/Documents/Michelle/lava/test_data/work/23/56ccf88c2979202de4aacd412bd78d/proteins.csv proteins.csv
    ln -s /Users/uwvirongs/Documents/Michelle/lava/test_data/work/b4/aa5f41d5458c1531e7a7578e6d9942/Example1_file2.fastq.genomecov Example1_file2.fastq.genomecov
    ln -s /Users/uwvirongs/Documents/Michelle/lava/test_data/work/bd/896b805204a8625bc494bca48abf85/Example1_file1.fastq.genomecov Example1_file1.fastq.genomecov
    ln -s /Users/uwvirongs/Documents/Michelle/lava/test_data/work/60/70bc9ec896d16148fb89cdaaf8832c/Example1_file1.fastq.vcf Example1_file1.fastq.vcf
    ln -s /Users/uwvirongs/Documents/Michelle/lava/test_data/work/05/f211861af5e1b3ba03d44630ec02b5/Example1_file2.fastq.vcf Example1_file2.fastq.vcf
    ln -s /Users/uwvirongs/Documents/Michelle/lava/test_data/work/43/689d6416d08c1fbf54a4b27043cd1c/ribosomal_start.txt ribosomal_start.txt
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR1 USR2

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A)"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /Users/uwvirongs/Documents/Michelle/lava/test_data/work/9a/d5c81153edb9052478b8d5b2e55a7e/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    set +e
    local ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
